### ISSUE TITLE
Counterfeit

### ISSUE THREAD

**Issue by tarun-varier** [JohnnyPhil995/Pac-Man#1]
Ayy buddy, I know this shit ain't made by u... come tha fuck on, admit it

**Comment by tarun-varier** [comment]
not like I giv a fuck but... come on

**Comment by JohnnyPhil995** [comment]
Okay
Firstly, stop cursing a lot, because it isn’t polite
And, secondly, I didn’t do it... I looked up a tutorial to make it, okay? I
admitted it.
-- 
Regards,

Jonathan.

**Comment by tarun-varier** [comment]
**Dear fuckin [boomer](https://github.com/JohnnyPhil995),**

- [ ] first of all, github issues ain't meant to be addressed like letters
- [ ] second of all, swearin is meant to be like a bond of friendship aaand it is very kool
- [ ] third of all, if u r worried that ppl might check out yo repo and be like 'oh no, this mf is swearin, no fuckin way', nah bro, that ain't happenin, I guarantee
- [ ] fourth of all, stop bein a pussy

![output-onlinepngtools](https://user-images.githubusercontent.com/63459975/94924689-a22ae080-04db-11eb-8c8e-a789f4fc0d38.png)

**_yo boi television signin off_**
